site_name: Zero to Mastery Learn PyTorch for Deep Learning
site_url: https://www.learnpytorch.io

repo_url: https://github.com/mrdbourke/pytorch-deep-learning/
repo_name: mrdbourke/pytorch_deep_learning

theme:
  name: material
  logo: assets/ztm-logo-and-pytorch-logo.png
  favicon: assets/ztm-logo-and-pytorch-logo.png
  features:
    - navigation.instant
    - navigation.top
  palette:
    primary: black

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
 - mkdocs-jupyter
 - search
 - social

edit_uri: ""

nav:
  - Home: 'index.md'
  - 00. Getting started with PyTorch: '00_pytorch_fundamentals.ipynb'
  - 01. PyTorch workflow: '01_pytorch_workflow.ipynb'
  - 02. PyTorch classification: '02_pytorch_classification.ipynb'
  - 03. PyTorch computer vision: '03_pytorch_computer_vision.ipynb'
  - 04. PyTorch custom datasets: '04_pytorch_custom_datasets.ipynb'
  - 05. PyTorch Going Modular: '05_pytorch_going_modular.md'
  - 06. PyTorch transfer learning: '06_pytorch_transfer_learning.ipynb'
  - 07. PyTorch experiment tracking: '07_pytorch_experiment_tracking.ipynb'
  - 08. PyTorch paper replicating: '08_pytorch_paper_replicating.ipynb'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mrdbourke
    - icon: fontawesome/brands/github
      link: https://github.com/mrdbourke/pytorch-deep-learning
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCr8O8l5cCX85Oem1d18EezQ
